create table if not exists human_managers
(
    human_manager_id            int         null,
    is_commish                  tinyint     null,
    first_name                  varchar(50) null,
    last_name                   varchar(50) null,
    nick_name                   varchar(50) null,
    age                         smallint    null,
    date_of_birth               date        null,
    city_of_birth_id            int         null,
    nation_id                   int         null,
    second_nation_id            int         null,
    weight                      smallint    null,
    height                      smallint    null,
    retired                     tinyint     null,
    free_agent                  tinyint     null,
    league_id                   int         null,
    last_league_id              int         null,
    team_id                     int         null,
    last_team_id                int         null,
    organization_id             int         null,
    last_organization_id        int         null,
    language_ids0               int         null,
    language_ids1               int         null,
    uniform_number              smallint    null,
    experience                  smallint    null,
    person_type                 smallint    null,
    bats                        smallint    null,
    throws                      smallint    null,
    personality_greed           smallint    null,
    personality_loyalty         smallint    null,
    personality_play_for_winner smallint    null,
    personality_work_ethic      smallint    null,
    personality_intelligence    smallint    null,
    personality_leader          smallint    null
);

