create table if not exists human_manager_history_batting_stats
(
    human_manager_id int      null,
    team_id          int      null,
    year             smallint null,
    league_id        int      null,
    sub_league_id    int      null,
    division_id      int      null,
    level_id         smallint null,
    split_id         smallint null,
    pa               int      null,
    ab               int      null,
    h                int      null,
    k                int      null,
    tb               int      null,
    s                int      null,
    d                int      null,
    t                int      null,
    hr               int      null,
    sb               int      null,
    cs               int      null,
    rbi              int      null,
    r                int      null,
    bb               int      null,
    ibb              int      null,
    hp               int      null,
    sh               int      null,
    sf               int      null,
    ci               int      null,
    gdp              int      null,
    g                int      null,
    gs               int      null,
    ebh              int      null,
    pitches_seen     int      null,
    avg              double   null,
    obp              double   null,
    slg              double   null,
    rc               double   null,
    rc27             double   null,
    iso              double   null,
    tavg             double   null,
    woba             double   null,
    ops              double   null,
    sbp              double   null
);

