create table if not exists league_history_batting_stats
(
    year         smallint null,
    team_id      int      null,
    game_id      int      null,
    league_id    int      null,
    level_id     smallint null,
    split_id     smallint null,
    pa           int      null,
    ab           int      null,
    h            int      null,
    k            int      null,
    tb           int      null,
    s            int      null,
    d            int      null,
    t            int      null,
    hr           int      null,
    sb           int      null,
    cs           int      null,
    rbi          int      null,
    r            int      null,
    bb           int      null,
    ibb          int      null,
    hp           int      null,
    sh           int      null,
    sf           int      null,
    ci           int      null,
    gdp          int      null,
    g            int      null,
    gs           int      null,
    ebh          int      null,
    pitches_seen int      null,
    avg          double   null,
    obp          double   null,
    slg          double   null,
    rc           double   null,
    rc27         double   null,
    iso          double   null,
    woba         double   null,
    ops          double   null,
    sbp          double   null,
    kp           double   null,
    bbp          double   null,
    wpa          double   null,
    babip        double   null
);

