create table if not exists league_history_fielding_stats
(
    year          smallint null,
    team_id       int      null,
    league_id     int      null,
    sub_league_id int      null,
    level_id      smallint null,
    split_id      smallint null,
    position      smallint null,
    g             int      null,
    gs            int      null,
    tc            int      null,
    a             int      null,
    po            int      null,
    e             int      null,
    dp            int      null,
    tp            int      null,
    pb            int      null,
    sba           int      null,
    rto           int      null,
    er            int      null,
    ip            int      null,
    ipf           int      null,
    pct           double   null,
    `range`       double   null,
    rtop          double   null,
    cera          double   null,
    zr            double   null,
    plays         int      null,
    plays_base    int      null,
    roe           int      null,
    eff           int      null,
    opps_0        int      null,
    opps_made_0   int      null,
    opps_1        int      null,
    opps_made_1   int      null,
    opps_2        int      null,
    opps_made_2   int      null,
    opps_3        int      null,
    opps_made_3   int      null,
    opps_4        int      null,
    opps_made_4   int      null,
    opps_5        int      null,
    opps_made_5   int      null,
    framing       double   null,
    arm           double   null
);

