create table if not exists players_fielding
(
    player_id                        int      null,
    team_id                          int      null,
    league_id                        int      null,
    position                         smallint null,
    role                             smallint null,
    fielding_ratings_infield_range   smallint null,
    fielding_ratings_infield_arm     smallint null,
    fielding_ratings_turn_doubleplay smallint null,
    fielding_ratings_outfield_range  smallint null,
    fielding_ratings_outfield_arm    smallint null,
    fielding_ratings_catcher_arm     smallint null,
    fielding_ratings_catcher_ability smallint null,
    fielding_ratings_infield_error   smallint null,
    fielding_ratings_outfield_error  smallint null,
    fielding_experience0             smallint null,
    fielding_experience1             smallint null,
    fielding_experience2             smallint null,
    fielding_experience3             smallint null,
    fielding_experience4             smallint null,
    fielding_experience5             smallint null,
    fielding_experience6             smallint null,
    fielding_experience7             smallint null,
    fielding_experience8             smallint null,
    fielding_experience9             smallint null,
    fielding_rating_pos1             smallint null,
    fielding_rating_pos2             smallint null,
    fielding_rating_pos3             smallint null,
    fielding_rating_pos4             smallint null,
    fielding_rating_pos5             smallint null,
    fielding_rating_pos6             smallint null,
    fielding_rating_pos7             smallint null,
    fielding_rating_pos8             smallint null,
    fielding_rating_pos9             smallint null
);

