create table if not exists players_career_fielding_stats
(
    player_id   int      null,
    year        smallint null,
    team_id     int      null,
    league_id   int      null,
    level_id    smallint null,
    split_id    smallint null,
    position    smallint null,
    tc          smallint null,
    a           smallint null,
    po          smallint null,
    er          smallint null,
    ip          smallint null,
    g           smallint null,
    gs          smallint null,
    e           smallint null,
    dp          smallint null,
    tp          smallint null,
    pb          smallint null,
    sba         smallint null,
    rto         smallint null,
    ipf         smallint null,
    plays       smallint null,
    plays_base  smallint null,
    roe         smallint null,
    opps_0      smallint null,
    opps_made_0 smallint null,
    opps_1      smallint null,
    opps_made_1 smallint null,
    opps_2      smallint null,
    opps_made_2 smallint null,
    opps_3      smallint null,
    opps_made_3 smallint null,
    opps_4      smallint null,
    opps_made_4 smallint null,
    opps_5      smallint null,
    opps_made_5 smallint null,
    framing     double   null,
    arm         double   null,
    zr          double   null
);

