create table if not exists players_contract
(
    player_id                     int      null,
    team_id                       int      null,
    league_id                     int      null,
    position                      smallint null,
    role                          smallint null,
    is_major                      tinyint  null,
    no_trade                      tinyint  null,
    last_year_team_option         tinyint  null,
    last_year_player_option       tinyint  null,
    last_year_vesting_option      tinyint  null,
    next_last_year_team_option    tinyint  null,
    next_last_year_player_option  tinyint  null,
    next_last_year_vesting_option tinyint  null,
    contract_team_id              int      null,
    contract_league_id            int      null,
    season_year                   int      null,
    salary0                       int      null,
    salary1                       int      null,
    salary2                       int      null,
    salary3                       int      null,
    salary4                       int      null,
    salary5                       int      null,
    salary6                       int      null,
    salary7                       int      null,
    salary8                       int      null,
    salary9                       int      null,
    years                         smallint null,
    current_year                  smallint null,
    minimum_pa                    smallint null,
    minimum_pa_bonus              int      null,
    minimum_ip                    smallint null,
    minimum_ip_bonus              int      null,
    mvp_bonus                     int      null,
    cyyoung_bonus                 int      null,
    allstar_bonus                 int      null,
    next_last_year_option_buyout  int      null,
    last_year_option_buyout       int      null,
    opt_out                       smallint null,
    opt_out_relegation            tinyint  null,
    retained                      smallint null
);

