create table if not exists players_career_batting_stats
(
    player_id    int      null,
    year         smallint null,
    team_id      int      null,
    game_id      int      null,
    league_id    int      null,
    level_id     smallint null,
    split_id     smallint null,
    position     smallint null,
    ab           smallint null,
    h            smallint null,
    k            smallint null,
    pa           smallint null,
    pitches_seen smallint null,
    g            smallint null,
    gs           smallint null,
    d            smallint null,
    t            smallint null,
    hr           smallint null,
    r            smallint null,
    rbi          smallint null,
    sb           smallint null,
    cs           smallint null,
    bb           smallint null,
    ibb          smallint null,
    gdp          smallint null,
    sh           smallint null,
    sf           smallint null,
    hp           smallint null,
    ci           smallint null,
    wpa          double   null,
    stint        smallint null,
    ubr          double   null,
    war          double   null
);

